apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: think2019
spec:
  containers:
  - name: webserver
    image: yigitpolat/webserver
  - name: busybox-sidecar
    image: kubilayceylan/webserver:port
